# Generated by Django 5.2.3 on 2025-07-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='note',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
