# Generated by Django 5.2.3 on 2025-07-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_student_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
