# Generated by Django 5.2.3 on 2025-07-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='note',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
